STCOM-756 Accordion css implementation
folio-org/stripes-components pull request #1422
Opened 2020-10-23 17:14 UTC by JohnC-80

Behavior of accordions in inventory prompted me to re-examine the way that Accordions are implemented - there had to be a better way. 
This uses CSS animation and an inner div to wrap the content. TIL: the visibility property can be "animated" - it just steps, so it's really more in applying the delay.
Also, it's functional....

2020-11-18 15:59 UTC, rasmuswoelk commented
I'll take a look at this soon!

2020-11-20 21:24 UTC, zburke approved these changes
Functionally, this looks great to me. Nice work!

Are there DOM changes that we should know about if folks have written custom interactors in their own repos?

2020-11-25 14:23 UTC, rasmuswoelk requested changes
Nice work overall! It's really a long overdue update for the accordion so I'm looking forward to getting these changes merged in!

The only thing I noticed is the collapse/expand transitions being a bit "janky". It looks like it's due to the margin-bottom being removed/applied on collapse/expand. It kinda jumps a bit just before the transition happens:

![2020-11-25 15 12 29](https://user-images.githubusercontent.com/640976/100238974-1fe5f800-2f31-11eb-90fe-ddae3c63e98a.gif)

I played around with a bit and I could get it to stop jumping by adding that spacing inside the content div. It could be solved by either adding an additional "inner"-element that has that extra margin or in the case below, I added an :after pseudo element to .content that has a height of 1rem. I also tweaked the transition a bit:

```css
.content {
  opacity: 0;
  visibility: hidden; /* inputs within will not be focusable */
  transition: transform 0.1s ease 0.5s, opacity 0.1s linear 0.5s, visibility 0.2s linear 0.5s;

  &.expanded {
    opacity: 1;
    visibility: visible;
    transform: translateY(0);
    transition: transform 0.15s ease-in-out 0.2s, opacity 0.15s ease-in-out;
  }

  &:after {
    content: '';
    height: 1rem;
    display: block;
    width: 100%;
  }
}
```

Updated transition:

![2020-11-25 15 10 20](https://user-images.githubusercontent.com/640976/100239338-95ea5f00-2f31-11eb-872f-a7576e5f6408.gif)

2020-12-01 15:25 UTC, JohnC-80 commented
@rasmuswoelk aw, you don't like the fade-in of content? Just kidding.. it's gone. Thanks for the adjustments!

2020-12-02 10:49 UTC, rasmuswoelk approved these changes

2020-12-08 21:34 UTC, merged

2020-12-09 16:07 UTC, BogdanDenis commented on lib/Accordion/Accordion.css
> +  z-index: 1;
Hi @JohnC-80, we've found one issue with updated Accordion in eHoldings application - part of content is cut off and disappears under an accordion that is below
![image](https://user-images.githubusercontent.com/19309423/101653405-f73d2280-3a47-11eb-8c18-4a6a54b0f112.png)

I was able to partly fix is by applying these styles:
```
.content-wrap.expanded {
  overflow: visible;
}
```
This fixes the cutoff issues, but still something wrong with z-indexes
![image](https://user-images.githubusercontent.com/19309423/101653716-4c793400-3a48-11eb-9d13-a81baa74db6a.png)

Adding
```
.content-wrap {
  z-index: 2;
}
```
This makes z-index equal to that of `<Headline>` element, which is defined in `interactionStyles.css:26`
![image](https://user-images.githubusercontent.com/19309423/101654039-b42f7f00-3a48-11eb-9ec1-a7397e184017.png)

Now I'm stuck at this point - both `Tags` and `Holding status` are accordions which have `z-index: 2`, `multiSelectMenu` has `z-index: 9999`.
Could you help me with this please?

2020-12-10 10:48 UTC, BogdanDenis commented on lib/Accordion/Accordion.css
> +  z-index: 1;
Also, we have a component that displays a list of items which is a "infinite scroll" type of list
https://folio-snapshot.dev.folio.org/eholdings/packages/19-6581?searchType=packages&q=ebsco
Here we should be able to scroll through all of the items, but the scroll isn't working now
You can see how it should work here
https://folio-goldenrod.dev.folio.org/eholdings/packages/19-6581?searchType=packages&q=ebsco

2020-12-10 11:06 UTC, BogdanDenis commented on lib/Accordion/Accordion.js
> +  const onToggle = typeof openProp === 'undefined' ? uncontrolledToggle : onToggleProp;
`openProp` here seems to be an undeclared variable

2020-12-10 13:09 UTC, yelyzavetakhokhlova commented
Hey @JohnC-80, we also have issues with content being cut off in data export accordions. ☹️
![image](https://user-images.githubusercontent.com/69502158/101776500-b3a2f100-3af9-11eb-87d4-a35c12cc53c5.png)