UIEH-1017: Fix a11y errors on Modal and ConfirmationModal components
folio-org/stripes-components pull request #1483
Opened 2021-01-06 15:25 UTC by BogdanDenis

## Description
A few ui-eholdings tests are failing due to accessibility issues [ARIA dialog and alertdialog nodes must have an accessible name](https://dequeuniversity.com/rules/axe/4.1/aria-dialog-name).
This PR is aimed at adding missing `aria-label` attribute to wrapping element of `<Modal>` and `<ConfirmationModal>` components

### Related PRs:

## Issues
[UIEH-1017](https://issues.folio.org/browse/UIEH-1017)

2021-01-08 23:07 UTC, JohnC-80 requested changes

2021-01-08 23:07 UTC, JohnC-80 commented on lib/Modal/Modal.js
> +                aria-label={rest['aria-label'] || props.ariaLabel}
line 152 below is applying this prop to the WrappingElement should be fulfilling this so long as the prop is being applied to the Modal component... if it isn't working and placing this here is the true fix, please remove line 152. Thanks!!

2021-01-11 09:51 UTC, BogdanDenis commented on lib/Modal/Modal.js
> +                aria-label={rest['aria-label'] || props.ariaLabel}
Applying `aria-label` to `WrappingElement` still gives an error, because that element doesn't have `role="dialog"`, but `<OverlayModal>` does

2021-01-12 03:24 UTC, zburke commented on lib/Modal/Modal.js
> +                aria-label={rest['aria-label'] || props.ariaLabel}
Thanks, @BogdanDenis, this explanation makes sense. Can you please remove Line 152 as @JohnC-80 requested?

2021-01-12 09:59 UTC, BogdanDenis commented on lib/Modal/Modal.js
> +                aria-label={rest['aria-label'] || props.ariaLabel}
@zburke sorry, I missed that I had to remove that line. Done now

2021-01-12 14:07 UTC, zburke approved these changes
Thanks for cleaning this up! Getting ARIA attributes correct can be really tricky and I really appreciate your attention to detail here.

2021-01-12 14:33 UTC, merged