Finish conversion from Tether to Popper.
folio-org/stripes-components pull request #1509
Opened 2021-02-12 20:47 UTC by JohnC-80

We still had 2 lingering usages of the Tether dependency within the library. Complete removal of the Tether dependency will have to wait for further usage analysis, but this change moves the last of our components that were using Tether over to using the Popper.js library.

2021-02-22 14:35 UTC, rasmuswoelk requested changes
Finally.. we get rid of tether for good! We should celebrate 😄 🎊 

Selection changes look good and it works as expected in Storybook. I pushed a minor fix for the example.

When testing the AutoSuggest, I noticed that it does not close on outside click or when you hit escape. This is most likely because the RootCloseWrapper is missing.

2021-02-22 14:35 UTC, rasmuswoelk commented on lib/Selection/SingleSelect.js
> -        <RootCloseWrapper onRootClose={this.handleRootClose} ref={this.selectList}>
We still need the RootCloseWrapper when using Popper. The Selection component is not currently closing on outside click or when hitting escape.

2021-03-12 16:05 UTC, JohnC-80 commented on lib/Selection/SingleSelect.js
> -        <RootCloseWrapper onRootClose={this.handleRootClose} ref={this.selectList}>
Updated (finally!)

2021-03-15 17:23 UTC, rasmuswoelk approved these changes

2021-03-26 16:38 UTC, merged