STCOM-815: Landmarks must have a unique role or role/label/title (AxeDevTools Error)
folio-org/stripes-components pull request #1521
Opened 2021-03-10 12:16 UTC by IhorKoba

## Ticket
https://issues.folio.org/browse/STCOM-815

## Changes
- Add `aria-label` attribute to default accordion header of `<DefaultAccordionHeader>` component to fix error about uniqueness of landmarks.

## Before
![image](https://user-images.githubusercontent.com/40805351/110627717-f634a200-81aa-11eb-810f-495ec15134ad.png)

## After
![image](https://user-images.githubusercontent.com/40805351/110627823-17958e00-81ab-11eb-802f-e89e19294592.png)

2021-03-10 14:11 UTC, zburke reviewed
I understand the a11y violation needs to be addressed, and this change technically does that, but I'm not sure a value like `accordion-toggle-button-foo` meets the spirit of the [description](https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html#ARIA14-description), "an accessible name". OTOH, maybe something is better than nothing? Dunno.

@JohnC-80, any thoughts here?

2021-03-10 15:56 UTC, IhorKoba commented
> I understand the a11y violation needs to be addressed, and this change technically does that, but I'm not sure a value like `accordion-toggle-button-foo` meets the spirit of the [description](https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html#ARIA14-description), "an accessible name". OTOH, maybe something is better than nothing? Dunno.
> 
> @JohnC-80, any thoughts here?

@zburke , I agree , that it would be nice to have some informative name, but as for me in that case it's more important to have correct connection between aria-label and aria-labeledby attributes like there https://dequeuniversity.com/rules/axe/4.1/landmark-unique?application=AxeChrome, and we have a lot of accordions with dynamically generated these names.

2021-03-10 16:25 UTC, zburke commented
Would it be better to stick an `id` on the `<div>` on line 80 and point to that with `aria-labelledby` here?

2021-03-11 21:28 UTC, JohnC-80 requested changes

2021-03-11 21:28 UTC, JohnC-80 commented on lib/Accordion/headers/DefaultAccordionHeader.js
> +            aria-label={`accordion-toggle-button-${id}`}
With regions, most if not all examples show them as labeled with an heading tag.. This is probably best for the regions role as a section of a page. DefaultAccordionHeader has `headingLevel: 3` as a default prop, which should render as an h3 when fed to the Headline component that it renders... (see line 59)

For some reason, this seems to be coming up as 'undefined' once it reaches the Headline.

I believe that once an h3 tag is rendered, rather than a div or other non-semantic elment, it will resolve this issue. In other places I see the tag has been provided in some other way - either ran explicit `headerProps: { headingLevel: 2}` or something like `label={<Headline tag="h3" ... ` `aria-labelledby should work fine on its own for the offending content "region"...

2021-03-11 21:30 UTC, JohnC-80 commented on lib/Accordion/headers/DefaultAccordionHeader.js
> +            aria-label={`accordion-toggle-button-${id}`}
We shouldn't do this with `aria-label` as it will override any meaningful text that's within the header for assistive technology. As you mentioned, with these id's being generated, it would announce something like "accordion-toggle-button-accordion6" 
- probably not quite explicit enough for an accessibility review.

2021-03-12 10:13 UTC, IhorKoba commented on lib/Accordion/headers/DefaultAccordionHeader.js
> +            aria-label={`accordion-toggle-button-${id}`}
Thanks for your comment!

So, for render default heading I thing we need to pass `defaultProps` in this way :
`const defaultProps = {
  headerProps: {
    headingLevel: 3,
  }
};`
instead of
`const defaultProps = {
  headingLevel: 3,
};`
because we’re getting this `headingLevel`  from `headerProps`  on line 46, and remove `headerProps` as an empty object from `<Accordion>`  component.
In that case `DefaultAccordionHeader`  component will be rendered with correct `h3` tag.
I applied that changes locally and now correct heading renders:

![image](https://user-images.githubusercontent.com/40805351/110925482-ed1f0e80-832b-11eb-9f5a-3a26af40ad50.png)

But when I run Axe check I steel got the same error message:

![image](https://user-images.githubusercontent.com/40805351/110925651-235c8e00-832c-11eb-9313-9b23c5787f7b.png)

2021-03-12 18:36 UTC, JohnC-80 commented
Commenting for persistence - So after some discussion about this issue, the fix to have the defaultAccordionHeader render its h3 out-of-box is a necessary one.  So we definitely want to keep that portion of this PR.

The culprit of the axe error is multiple rendered accordions with **Matching visible text labels**.  ie - an accordion named "Information" in the detail and the corresponding "Information" accordion in the edit page. This can happen in any application that uses the `<Layer>` component for rendering an edit view.

I feel that, given the context around the accordion, and the general DOM distance between the matching accordions, there probably won't be much *actual confusion around this from the AT user perspective - this error isn't a dire emergency - NOT having a heading structure, on the other hand, is one that should definitely be resolved (and this PR helps that in its new form. - thank you @IhorKoba !)

Other ways to resolve (aka, right things to do) - 
 - conditional rendering: if using `<Layer>`, hide the detail view's accordions when the edit view is open .
  or
 - use actual routing so that the only elements rendered are those within the form/Layer
  or
 - name the edit view accordions differently (probably more redundant than practical, but not to be left out)

We're going to include this documentation on the accordion component at first for others encountering the issue... and probably find an even more public place to put it with gotchas we run into with axe errors.

2021-03-12 19:02 UTC, JohnC-80 approved these changes

2021-03-15 13:49 UTC, merged