STCOM-865 Apply guidelines for the display of shortcut key combinatio…
folio-org/stripes-components pull request #1595
Opened 2021-07-20 14:07 UTC by CalamityC

…ns in an app's "Keyboard shortcuts" modal

* present shortcut key combinations in camel case with spaces (guideline 1) in KeyboardShortcutsModal
* add missing default shortcuts
* change description and order of default shortcuts (guideline 2)

2021-07-21 17:49 UTC, aditya-matukumalli requested changes

2021-07-21 17:49 UTC, aditya-matukumalli commented on lib/KeyboardShortcutsModal/KeyboardShortcutsModal.js
>    const shortcutsData = [];
This piece of code from L27-L49 could probably made a bit more concise.

```suggestion
 const shortcutsData = allCommands.map(({ label, shortcut }) => {
      const shortcutCommand = shortcut.replace(/ /g, '').split('+');
      const commandArray = shortcutCommand.map(cmd => upperFirst(cmd.toLowerCase()));
      let camelCasedShortcut;

      if (platform.includes('Mac')) {
        camelCasedShortcut = commandArray.join(' + ').replace('Mod', 'Cmd').replace('Alt', 'Option');
      } else {
        camelCasedShortcut = commandArray.join(' + ').replace('Mod', 'Ctrl');
      }

      return {
        'action': label,
        'shortcut': camelCasedShortcut,
      };
    });
```

2021-07-22 15:49 UTC, aditya-matukumalli approved these changes

2021-08-16 09:40 UTC, Jagusti commented
@aditya-matukumalli  @JohnC-80 is there something we need to do within ERM team to enable this to progress for merge?

2021-08-16 13:40 UTC, aditya-matukumalli commented
> @aditya-matukumalli @JohnC-80 is there something we need to do within ERM team to enable this to progress for merge?

This PR is still awaiting the confirmation of the final list of shortcut keys that need to go into stripes-components. Last I know, Khalilah and Gill are in talks about the final list.

2021-09-10 20:49 UTC, aditya-matukumalli commented
Closing this PR. All the changes from this PR has been pulled into the ongoing work in this branch https://github.com/folio-org/stripes-components/tree/export-keyboard-shortcuts-api .

2021-09-10 20:49 UTC, closed without merging