STCOM-889: Create a Conflict Detection banner
folio-org/stripes-components pull request #1666
Opened 2021-11-18 17:16 UTC by mariiaschv

## Description
Created a Conflict Detection banner which will be displayed when a conflict due to optimistic locking occurs.

Issue: [STCOM-889](https://issues.folio.org/browse/STCOM-889)

2021-11-18 18:25 UTC, zburke requested changes
This is a great start, but at minimum it needs tests and a readme. Please add a link to `/README.md` as well.

2021-11-18 18:58 UTC, zburke commented
From the ticket:

> Given the user views the Conflict detection banner
> When s/he clicks on the Cancel button OR "X"
> Then return to the previous page

does this mean we should be passing `dismissible` to the internal `<MessageBanner>`?

2021-11-19 07:40 UTC, mariiaschv commented
> From the ticket:
> 
> > Given the user views the Conflict detection banner
> > When s/he clicks on the Cancel button OR "X"
> > Then return to the previous page
> 
> does this mean we should be passing `dismissible` to the internal `<MessageBanner>`?

Hey, I believe this means that if user is on Edit page and a conflict due to optimistic locking occurs so that the banner appears, if the user wants to leave the Edit page by clicking Cancel button or "X" he should be able to do that without any impediments, just going back to the previous page.

2021-11-23 12:46 UTC, BogdanDenis approved these changes

2021-11-24 11:06 UTC, Vladyslav-Velytskyi approved these changes

2021-11-29 12:20 UTC, merged