STCOM-898: Layout > Add textStart, textEnd properties
folio-org/stripes-components pull request #1705
Opened 2022-01-11 09:57 UTC by mariiaschv

## Purpose
Adds new `text-start`, `text-end` classNames to `<Layout>` component to support both LTR and RTL languages.

## Issues
[STCOM-898](https://issues.folio.org/browse/STCOM-898)

2022-01-11 10:50 UTC, zburke approved these changes
LGTM, but I am not an RTL expert. @JohnC-80, what do you think?

2022-01-11 11:57 UTC, Svitlana-Korol approved these changes

2022-01-11 21:19 UTC, JohnC-80 approved these changes
Approved - Thanks!!

2022-01-12 10:11 UTC, BogdanDenis requested changes

2022-01-12 10:11 UTC, BogdanDenis commented on lib/Layout/stories/classNamePropertiesMapping.js
> +  'text-start': 'text-align: start;',
I think it's good to be consistent with names and use `textStart` and `textEnd` here

2022-01-12 10:22 UTC, mariiaschv commented on lib/Layout/stories/classNamePropertiesMapping.js
> +  'text-start': 'text-align: start;',
I agree with you about consistency but the reason I used `text-start` and `text-end` is [this comment](https://issues.folio.org/browse/STCOM-897?focusedCommentId=116278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-116278) by @zburke where he said that 

> Kinda ugly that we have multiple naming conventions in place there, but I think we are leaning toward dash-separated-names now

But if you still think the names should be changed to camelCase I will do it, no problem :)

2022-01-12 10:54 UTC, BogdanDenis commented on lib/Layout/stories/classNamePropertiesMapping.js
> +  'text-start': 'text-align: start;',
@mariiaschv oh I didn't notice that comment... then it's ok to merge as is

2022-01-12 10:59 UTC, BogdanDenis approved these changes

2022-01-12 11:43 UTC, merged