STCOM-919: Advanced Search component
folio-org/stripes-components pull request #1706
Opened 2022-01-18 17:20 UTC by BogdanDenis

## Description
Added new `<AdvancedSearch>` component

## Screenshots

https://user-images.githubusercontent.com/19309423/149986259-7794d886-b39f-44e8-95fe-5ef61523f636.mp4

## Issues
[STCOM-919](https://issues.folio.org/browse/STCOM-919)

## Related PRs
https://github.com/folio-org/stripes-testing/pull/191

2022-01-19 16:18 UTC, zburke commented
@BogdanDenis , do you anticipate this being available in Lotus? The feature-freeze deadline for stripes is either 2022-01-17 or -21, depending on which value from the [Lotus roadmap](https://wiki.folio.org/pages/viewpage.action?pageId=73534630).

2022-01-19 16:42 UTC, JohnC-80 approved these changes

2022-01-19 17:14 UTC, mariiaschv requested changes

2022-01-19 17:14 UTC, mariiaschv commented on lib/AdvancedSearch/AdvancedSearch.js
> +  }), [handleSearch]);
```suggestion
  const handlers = useMemo(() => ({
    search: handleSearch,
  }), [handleSearch]);
```

2022-01-19 17:14 UTC, mariiaschv commented on lib/MultiSelection/MultiSelection.js
> +                    >
Is it needed to put `className` on the separate line?

2022-01-19 17:14 UTC, mariiaschv commented on lib/AdvancedSearch/utilities/defaultQueryBuilder.js
> +    // query string is alread formatted, else it would result in smthn like query==subject==Music
Small typo here :)
```suggestion
    // query string is already formatted, else it would result in smthn like query==subject==Music
```

2022-01-19 19:34 UTC, Svitlana-Korol approved these changes

2022-01-20 08:49 UTC, BogdanDenis commented
> @BogdanDenis , do you anticipate this being available in Lotus? The feature-freeze deadline for stripes is either 2022-01-17 or -21, depending on which value from the [Lotus roadmap](https://wiki.folio.org/pages/viewpage.action?pageId=73534630).

Yes, this feature is planned to be released in Lotus

2022-01-20 08:55 UTC, mariiaschv approved these changes

2022-01-25 15:23 UTC, merged