STCOM-923 Add the ability to hide the number of pages and leave the buttons not disabled
folio-org/stripes-components pull request #1709
Opened 2022-01-25 17:24 UTC by vashjs

**Purpose:**

For tasks 
https://issues.folio.org/browse/UIIN-1890
https://issues.folio.org/browse/UIIN-1897

we need to be able to navigate not by offsets + indexes, but by making a new request to the server, while the next and prev buttons should be active. Also we should  add the ability to hide the the label with number of pages and propagate the direction to parent component.

2022-01-25 17:38 UTC, JohnC-80 requested changes

2022-01-25 17:38 UTC, JohnC-80 commented on lib/MultiColumnList/MCLRenderer.js
> +    } else if (pagingType === pagingTypes.LOAD_MORE || pagingType === pagingTypes.SCROLL) {
```suggestion
    } else if (pagingType === pagingTypes.LOAD_MORE || pagingType === pagingTypes.PREV_NEXT) {
```

2022-01-25 17:50 UTC, vashjs commented on lib/MultiColumnList/MCLRenderer.js
> +    } else if (pagingType === pagingTypes.LOAD_MORE || pagingType === pagingTypes.SCROLL) {
Thanks, my bad

2022-01-26 15:03 UTC, UladzislauKutarkin approved these changes

2022-01-26 15:11 UTC, JohnC-80 approved these changes

2022-01-26 16:28 UTC, merged