UIU-2037: Settings > Users > Heading Level updates
folio-org/stripes-components pull request #1716
Opened 2022-02-02 11:11 UTC by OleksandrHladchenko1

HI, @zburke! In scope of my task I need to replace DIV for General, Fee/Fine, Patron blocks with H3 tag. So, in NavListSection I added tag prop to Headline component. What do you think about this change? Can we apply it for my task? 
Ref: https://issues.folio.org/browse/UIU-2037

2022-02-02 14:17 UTC, JohnC-80 requested changes
It's probably best to expose this as a prop to be used at the module level rather than it default to h3's... this way the level can be adjusted per-use. While it's best to have heading elements rather than divs, it can also be problematic if the incorrect heading level is used.

2022-02-03 19:07 UTC, zburke requested changes
Please fix the lint error by configuring prop-types, then this looks good. Please note I cloned UIU-2037 to STCOM-929 since this change will be in stripes-components rather than ui-users.

2022-02-07 14:17 UTC, JohnC-80 approved these changes

2022-02-07 18:38 UTC, zburke approved these changes

2022-02-08 16:41 UTC, merged