STCOM-934: Advanced search does not work when editing Advanced Search box
folio-org/stripes-components pull request #1726
Opened 2022-02-18 16:55 UTC by Svitlana-Korol

## Description
Advanced search not work when editing Advanced Search box

## Issues
[STCOM-934](https://issues.folio.org/browse/STCOM-934)

2022-02-23 11:25 UTC, BogdanDenis requested changes

2022-02-23 11:25 UTC, BogdanDenis commented on lib/AdvancedSearch/AdvancedSearch.js
> +  useEffect(() => {
I think this is not needed because we have similar `useEffect` later. Please check if everything is working correctly without this `useEffect`

2022-02-23 11:25 UTC, BogdanDenis commented on lib/AdvancedSearch/tests/AdvancedSearch-test.js
> +  const onRowsChangeSpy = sinon.spy();
This prop is not available anymore, we should remove it from tests

2022-02-23 11:25 UTC, BogdanDenis commented on lib/AdvancedSearch/tests/AdvancedSearch-test.js
>          {({ resetRows }) => (
We should also test that `rowState` is passed correctly to children
To test this we can add a button here. When it's clicked it should call a mock function with `rowState` and in a test we should check that it was called with correct items

2022-03-07 10:53 UTC, mariiaschv requested changes

2022-03-07 10:53 UTC, mariiaschv commented on CHANGELOG.md
> +* Advanced search does not work when editing Advanced Search box.Refs STCOM-934.
Please, add space here to be consistent with all the other lines above.
```suggestion
* Advanced search does not work when editing Advanced Search box. Refs STCOM-934.
```

2022-03-07 10:53 UTC, mariiaschv commented on lib/AdvancedSearch/tests/AdvancedSearch-test.js
> +          <>owStates
Shouldn't it be just `<>` here? Please recheck.

2022-03-07 11:39 UTC, Svitlana-Korol commented on lib/AdvancedSearch/tests/AdvancedSearch-test.js
> +          <>owStates
Thanks, I fixed it!

2022-03-09 04:49 UTC, NikitaSedyx commented
@Svitlana-Korol there are failed tests, please fix them

2022-03-09 04:50 UTC, NikitaSedyx commented on lib/AdvancedSearch/AdvancedSearch.js
> +        const [_, operator = '', query] = match;
you can simply do `[, operator = '', query]` to avoid warning

2022-03-09 04:52 UTC, NikitaSedyx commented on lib/AdvancedSearch/AdvancedSearch.js
> +  const splitQueryRows = (rows) => {
can it be moved out from component?

2022-03-09 04:53 UTC, NikitaSedyx commented on lib/AdvancedSearch/AdvancedSearch.js
> +  }, [queryBuilder, onSearch, rowState]);
why is rowFormatted removed from dependencies?

2022-03-09 04:53 UTC, NikitaSedyx commented on lib/AdvancedSearch/AdvancedSearch.js
> +  useEffect(() => {
I'd suggest to create hook to all of this stuff, too many code that can be moved from component

2022-03-11 10:18 UTC, Svitlana-Korol commented on lib/AdvancedSearch/AdvancedSearch.js
> +        const [_, operator = '', query] = match;
You are right, thanks!

2022-03-11 10:18 UTC, Svitlana-Korol commented on lib/AdvancedSearch/AdvancedSearch.js
> +  }, [queryBuilder, onSearch, rowState]);
Thanks, I fixed it.

2022-03-16 12:58 UTC, NikitaSedyx commented
your component still has code that can be moved out from it, custom hook is good way to do it

2022-03-17 11:12 UTC, BogdanDenis commented on lib/AdvancedSearch/AdvancedSearch.js
> +    const splitRows = filterFilledRows(splitQueryRows(rowState));
I think passing filtered rows to `onSearch` caused an exception, could you check please?
If there's an exception - we should change the code to:
```
const splitRows = splitQueryRows(rowState);

if (!splitRows.length) {
      setShowEmptyFirstRowMessage(true);

      return;
    }

    setShowEmptyFirstRowMessage(false);
    
    const query = queryBuilder(filterFilledRows(splitRows), rowFormatter);
    onSearch(query, splitRows);
```

2022-03-17 15:55 UTC, BogdanDenis approved these changes

2022-03-18 04:55 UTC, NikitaSedyx commented on hooks/useAdvancedSearch/index.js
> +
extra line

2022-03-18 04:56 UTC, NikitaSedyx commented on hooks/useAdvancedSearch/useAdvancedSearch.js
> +import {
please move it to AdvancedSearch component, this hook is not smth common and shouldn't be placed in hooks folder

2022-03-18 04:57 UTC, NikitaSedyx commented on hooks/useAdvancedSearch/useAdvancedSearch.js
> +
extra line

2022-03-18 04:58 UTC, NikitaSedyx commented on lib/AdvancedSearch/utilities/filterFilledRows.js
> +
extra lines, please configure your editor to remove them automatically

2022-03-18 04:58 UTC, NikitaSedyx commented on lib/AdvancedSearch/utilities/splitQueryRows.js
> +
the same

2022-03-18 04:59 UTC, NikitaSedyx commented
some codestyle issues, the rest is lhtm

2022-03-18 11:40 UTC, mariiaschv approved these changes

2022-03-18 12:39 UTC, NikitaSedyx approved these changes

2022-03-18 12:41 UTC, merged