STCOM-936 NoValue component doesn't have role
folio-org/stripes-components pull request #1729
Opened 2022-02-23 11:42 UTC by NikitaSedyx

purpose: https://issues.folio.org/browse/STCOM-936
axe reports many issues when NoValue component is displayed

2022-02-23 11:49 UTC, AndreiShumski2 approved these changes

2022-02-23 11:50 UTC, usavkov-epam approved these changes

2022-02-23 19:14 UTC, JohnC-80 requested changes

2022-02-23 19:14 UTC, JohnC-80 commented on lib/NoValue/NoValue.js
>            aria-label={ariaLabel || message}
This error probably occurs due to the aria-label on an otherwise non-interactable element. 
I think we could remove this `ariaLabel` attribute, and instead, render a span with an `sr-only` class (a globally available CSS class.) This would be better than applying a textbox role to something that isn't a textbox.

2022-02-23 19:19 UTC, NikitaSedyx commented on lib/NoValue/NoValue.js
>            aria-label={ariaLabel || message}
yep, it's because of ariaLabel, not sure I got what `sr-only` class is, but I'll try

as for now ariaLabel looks reasonable to me to tell what `-` means in key values

2022-02-23 20:58 UTC, JohnC-80 commented on lib/NoValue/NoValue.js
>            aria-label={ariaLabel || message}
Thanks. You don't have to import any CSS or anything... just mark up as `<span className="sr-only">{message || ariaLabel}</span>` . You can think of roles as a promise to assistive technology that the element behaves in a certain way, so telling it that a span is a `textbox` isn't the best way, although it does resolve the axe error. Aria-labels require focus in order to be announced, which requires tabindex and more axe and probably more axe errors since it's only a span and not something that's interactive/with an interactive role.

2022-02-24 04:03 UTC, NikitaSedyx commented on lib/NoValue/NoValue.js
>            aria-label={ariaLabel || message}
@JohnC-80 got it, thank you!

yep, this makes more sense, applied changes with sr class and aria-hidden, please review one more time

2022-02-24 17:45 UTC, JohnC-80 approved these changes
Awesome. Thank You @NikitaSedyx .

2022-02-25 08:20 UTC, merged