STCOM-942 Selection - possible axe gotcha
folio-org/stripes-components pull request #1738
Opened 2022-02-25 18:37 UTC by JohnC-80

not providing a label to Selection could result in the error:
```
 Selection
    × does not have axe issues - Selection
      Chrome 98.0.4758.102 (Windows 10)
    AxeError:  Axe violation(s): 
     Issue #1: button-name - Buttons must have discernible text
        description: Ensures buttons have discernible text
      helpUrl: https://dequeuniversity.com/rules/axe/4.4/button-name?application=axeAPI
    
        Sample issue (1 of 1 detections)
          html: <button type="button" aria-expanded="false" aria-labelledby="selected-testingId-item" aria-haspopup="listbox" class="selectionControl---1j1xE formControl---3BY__" id="testingId" aria-owns="sl-testingId"><div class="singleValue---1vQYM" id="selected-testingId-item"></div></button>
        target: #testingId
    
          Failure Summary:
            Fix any of the following:
          -  Element does not have inner text that is visible to screen readers
          -  aria-label attribute does not exist or is empty
          -  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
          -  Element has no title attribute
          -  Element's default semantics were not overridden with role="none" or role="presentation"   
    
        at C:/Users/JCoburn/AppData/Local/Temp/_karma_webpack_764450/commons.js:301292:23
 ```

2022-03-04 19:56 UTC, zburke requested changes
Don't for get i18n when working on a11y :)

2022-03-04 19:56 UTC, zburke commented on lib/Selection/SingleSelect.js
> +            <span className="sr-only">select control</span>
How about `<FormattedMessage id="stripes-components.selection.selectControl" />`

2022-03-09 18:38 UTC, zburke approved these changes
LGTM. Yay a11y!

2022-03-11 18:59 UTC, ryandberger approved these changes

2022-03-23 18:41 UTC, merged