STCOM-948: Add 'aria-expanded' attr to IconButton
folio-org/stripes-components pull request #1742
Opened 2022-03-03 15:06 UTC by mariia-aloshyna

## Purpose
There is an accessibility issue in users app Open Loans List: "Elements must only use allowed ARIA attributes". This happens because the button's 'aria-expanded' attribute is extended to child elements.

## Approach
- Catch the attribute and assign it manually to the button

## Ref
https://issues.folio.org/browse/STCOM-948

2022-03-03 18:56 UTC, zburke requested changes
Thank you for a clear explanation of the problem and how this change addresses it! Pulling `aria-expanded` out of the values that cascade down makes sense to me. @JohnC-80 , do you agree? 

Please add a prop-types entry for this to clean up the lint warnings.

2022-03-04 15:17 UTC, zburke requested changes
So close! Please clean up the prop-types ordering and then I think we're done. Agreed, @JohnC-80?

2022-03-04 15:17 UTC, zburke commented on lib/IconButton/IconButton.js
> +  'aria-expanded': PropTypes.string,
Pedantic: as noted by lint prop-types need to be sorted alphabetically so this should be added at the top of the list.

2022-03-04 15:18 UTC, JohnC-80 approved these changes
#1737 was a similar issue - it adds `aria-haspopup` as well.
If we get many more of these, we might do something to consolidate the `aria-` props somehow without adding new proptypes, but for now, this is the way....

2022-03-04 17:00 UTC, mariia-aloshyna commented
Thanks for review @zburke and @JohnC-80! Prop-types are cleaned up.

2022-03-04 17:15 UTC, merged