Button: 'Link' style should behave as expected
folio-org/stripes-components pull request #1790
Opened 2022-05-04 12:19 UTC by Svitlana-Korol

## Description
'Link' style should behave as expected

## Issues
[STCOM-938](https://issues.folio.org/browse/STCOM-938)

2022-05-04 15:05 UTC, JohnC-80 requested changes
Thanks! Please switch the colors to use variables (similar to TextLink component: https://github.com/folio-org/stripes-components/blob/master/lib/TextLink/TextLink.css ) rather than hard-coded values.

2022-05-05 12:07 UTC, Svitlana-Korol commented
> Thanks! Please switch the colors to use variables (similar to TextLink component: https://github.com/folio-org/stripes-components/blob/master/lib/TextLink/TextLink.css ) rather than hard-coded values.

@JohnC-80 ,  I fixed it, thanks!

2022-05-05 14:27 UTC, JohnC-80 approved these changes

2022-05-06 12:57 UTC, mariiaschv approved these changes

2022-05-06 13:37 UTC, merged