STCOM-999 Remove paginationBoundaries prop from MCLRenderer and PrevNextPaginationRow components
folio-org/stripes-components pull request #1808
Opened 2022-05-30 10:46 UTC by vashjs

paginationBoundaries - this property is no longer needed, since by using activeNext and activePrevious we can achieve the same goals and disable the next and prev buttons.

2022-05-30 11:09 UTC, UladzislauKutarkin approved these changes

2022-05-30 11:10 UTC, UladzislauKutarkin reviewed
@vashjs update Changelog.md and readme.md about props

2022-05-31 15:16 UTC, JohnC-80 commented
Since this PR is removing props, that's technically a breaking change... The way we like to handle these things is to deprecate the props via `deprecate` from `prop-types-extra` now and go ahead and remove it from documentation, etc... then when stripes-components goes through a major feature update that would incur a major version, we'll do the actual removal then (along with other deprecated props in the library)... you can see an example of the deprecation here: https://github.com/folio-org/stripes-components/blob/893ea19b2e8a0820b8ce462aaa78cefd7ed736ba/lib/Headline/Headline.js#L59

As always, thank you for the work!

2022-05-31 16:01 UTC, vashjs commented
> Since this PR is removing props, that's technically a breaking change... The way we like to handle these things is to deprecate the props via `deprecate` from `prop-types-extra` now and go ahead and remove it from documentation, etc... then when stripes-components goes through a major feature update that would incur a major version, we'll do the actual removal then (along with other deprecated props in the library)... you can see an example of the deprecation here:
> 
> https://github.com/folio-org/stripes-components/blob/893ea19b2e8a0820b8ce462aaa78cefd7ed736ba/lib/Headline/Headline.js#L59
> 
> As always, thank you for the work!

@JohnC-80  Thanks for your update, fixed.

2022-05-31 16:32 UTC, zburke requested changes
Thanks for implementing `deprecate()` as @JohnC-80 suggested; that's perfect! Now we just need to get lint to run cleanly and we can merge this!

2022-05-31 16:32 UTC, zburke commented on lib/MultiColumnList/MCLRenderer.js
> +    paginationBoundaries: deprecated(PropTypes.bool), // will be removed in next major release. Use pagingCanGoPrevious and pagingCanGoNext instead.
Sigh; lint. How about 
```
// use pagingCanGoPrevious and pagingCanGoNext instead.
paginationBoundaries: deprecated(PropTypes.bool), 
```

2022-05-31 17:26 UTC, vashjs commented on lib/MultiColumnList/MCLRenderer.js
> +    paginationBoundaries: deprecated(PropTypes.bool), // will be removed in next major release. Use pagingCanGoPrevious and pagingCanGoNext instead.
@zburke  thanks, fixed

2022-05-31 18:16 UTC, zburke approved these changes

2022-05-31 20:00 UTC, merged