UIIN-2079 - Browse contributors. Placeholder match does not look right in the contributor column
folio-org/stripes-components pull request #1841
Opened 2022-06-27 11:09 UTC by Terala-Priyanka

## Description
This PR adds additional style to the cell rendered in the search result list rendered using MCLRenderer, in order the placeholder text is wrapped across cells in the row.

## Screenshots
![nckt7qBp5E](https://user-images.githubusercontent.com/104053200/175927883-ecd80e9d-0c83-43a5-a0f7-33fe65d37b69.gif)

## Issues
[UIIN-2079](https://issues.folio.org/browse/UIIN-2079)

2022-06-27 13:28 UTC, JohnC-80 commented
This is an app-level feature/behavior. It should be applied at the app level through the 'resultRowFormatter' that's being passed to the `SearchAndSort` component rather than a special case added to the component.

2022-06-28 07:51 UTC, BogdanDenis requested changes

2022-06-28 07:51 UTC, BogdanDenis commented on CHANGELOG.md
> +* Browse contributors. Placeholder match does not look right in the contributor column. Refs UIIN-2079
Please use ticket number from stripes-components Jira project

2022-06-28 07:51 UTC, BogdanDenis commented on lib/MultiColumnList/MCLRenderer.js
> +            style={rowData.isAnchor && !!value ? { ...cellStyle, overflow: 'visible' } : cellStyle}
Please move this conditional property to around line 1387, there's already some logic that builds `cellStyle` object and I think it'll be good to group it together

2022-07-04 09:36 UTC, closed without merging