STCOM-1058: After click submit button disable the confirmation button in ConfirmationModal component
folio-org/stripes-components pull request #1912
Opened 2022-11-22 12:43 UTC by OleksandrHladchenko1

## Link
[STCOM-1058](https://issues.folio.org/browse/STCOM-1058)

https://user-images.githubusercontent.com/85172747/203316697-4bb00270-d015-4082-b97f-bdc314e93020.mp4

2022-11-22 13:23 UTC, zburke requested changes
I'm glad to see this useful behavior. Please add a test that confirms it works as expected.

2022-11-25 12:24 UTC, OleksandrHladchenko1 commented
Done! 
cc: @zburke @JohnC-80

2022-11-28 18:41 UTC, JohnC-80 requested changes
Thanks you for adding the test! Please add a documentation bit to https://github.com/folio-org/stripes-components/tree/master/lib/ConfirmationModal#readme with the new prop.

2022-11-29 13:55 UTC, mkuklis approved these changes

2022-11-29 13:57 UTC, zburke approved these changes

2022-11-29 14:04 UTC, merged