Update eslint, handle lint
folio-org/stripes-components pull request #1941
Opened 2023-01-04 22:28 UTC by JohnC-80

This update bumps the eslint dependency to 8.31.0 - a whole breaking version -
And it exposes a handful of noted issues that were not previously detected including
- missing semicolons (ignored in `eslintrc` - this never presented a problem)
- functions used as jsx props that *could cause re-renders...
- unused or undeclared prop-types.

Merge/review of this is pending testing of affected components within modules.

2023-01-09 15:18 UTC, zburke reviewed
I set this branch in the dev-deps for ui-users and ui-requests but hit a bunch of test failures related to `require.context` 😕: 
```
$ yarn jest ./src/index.test.js 
yarn run v1.22.19
$ /Users/zburke/projects/folio-org/ui-requests/node_modules/.bin/jest ./src/index.test.js
 FAIL  src/index.test.js
  ● Test suite failed to run

    TypeError: require.context is not a function

      2 |
      3 | jest.mock('@folio/stripes/components', () => ({
    > 4 |   ...jest.requireActual('@folio/stripes/components'),
        |           ^
      5 |   Accordion: jest.fn(({ children, label }) => (
      6 |     <div>
      7 |       {label}

      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/Icon/icons.js:12:21)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/Icon/Icon.js:6:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/Icon/index.js:1:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/Label/Label.js:9:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/Label/index.js:1:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/TextField/TextField.js:8:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/TextField/index.js:1:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/AutoSuggest/AutoSuggest.js:9:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/lib/AutoSuggest/index.js:1:1)
      at Object.<anonymous> (node_modules/@folio/stripes/node_modules/@folio/stripes-components/index.js:2:1)
      at Object.<anonymous> (node_modules/@folio/stripes/components/index.js:1:1)
      at test/jest/__mock__/stripesComponents.mock.js:4:11
      at Object.<anonymous> (src/index.js:7:1)
      at Object.<anonymous> (src/index.test.js:7:1)
```
My only substantive feedback is about where that `semi` rule belongs: here or in eslint-config-stripes?

2023-01-10 12:49 UTC, BogdanDenis approved these changes

2023-01-13 21:27 UTC, JohnC-80 commented on .eslintrc
>      }
Yes, I think it should be in eslint-config-stripes. If teams want to enforce particular rules, they can do it in their own repos.

2023-01-16 12:21 UTC, zburke requested changes
Let's remove the `semi` rule change. I don't think we actually want it, and if we did this is the wrong place for it. 

Additionally, I worry sniffing the env to avoid `context.require` could bite us too. If something has changed in our env and mocks in other repos are suddenly not working, fine, do it to get back on track, but then let's file a ticket to investigate and remove the workaround.

2023-01-16 12:21 UTC, zburke commented on .eslintrc
>      }
On further review, I don't think we need to change the `semi` rule at all, whether for production code or for tests. Lint is griping about it now not because its rule changed but because our impl changed from `function foo...` to `const foo...`.

As to letting teams customize their own repos with their own exceptions, I would push back on that too. `eslint-config-stripes` benefits us the most when it's used the same way everywhere -- it's the whole reason this repo exists! -- so I would prefer not to see rules changing from repo to repo. Let's talk about this at #stripes-arch, or start a convo on that channel to see what other folks think.

2023-01-17 14:40 UTC, JohnC-80 commented on .eslintrc
>      }
Hmm... something changed - perhaps an inherited config? - but I'm not sure it's the implementation in all the places - If I turn this rule on, I have 222 errors for missing semis... these are most likely class properties from unchanged class-based component files.

2023-01-17 17:02 UTC, zburke commented on .eslintrc
>      }
Oooh, you're right about 200+ errors. I didn't get those on my initial run, but I see them now; must be a PEBKAC error 🤦 . Looking at the code, I think those errors are legit though: we've always intended for assignment expressions to be terminated by a semicolon, right?

2023-01-17 19:53 UTC, JohnC-80 commented on .eslintrc
>      }
In hindsight, it makes better sense for semicolons to go in all of these places... there's a chance that eslint suggested against it at the time with its 'unnecessary semicolon' gripe (okay, so the interpreter will just inject one there, can I please place one there anyways, so my JS code doesn't resemble python?) 
Let's merge this as-is and
- revisit the jsdom cludge in the future
- close the `eslint-config-stripes` PR (at least for now)
- run an eslint with `--fix` and turn the rule back on in another PR to inject all those semicolons.

2023-01-18 16:26 UTC, zburke commented on .eslintrc
>      }
Alright, we can move semicolon handling to [STCOM-1077](https://issues.folio.org/browse/STCOM-1077).

2023-01-18 16:28 UTC, zburke commented on lib/Icon/icons.js
> +}
It seems the expedient approach is to allow this hack for now and revisit in [STCOM-1078](https://issues.folio.org/browse/STCOM-1078) since it isn't obvious why it's suddenly becoming a problem given that it wasn't before.

2023-01-18 16:30 UTC, zburke approved these changes
I don't love the `require.context` hack and wish I understand where the change in semicolon rules is coming from, given this is supposed to be handled by `eslint-config-stripes`, but with [STCOM-1078](https://issues.folio.org/browse/STCOM-1078) and [STCOM-1077](https://issues.folio.org/browse/STCOM-1077) filed to handle those, I'm happy to merge this as-is so we can move ahead without losing track of our desire to investigate those further/later.

2023-01-18 16:41 UTC, merged