STCOM-1110: Add correct validation of data
folio-org/stripes-components pull request #1998
Opened 2023-03-06 08:21 UTC by daniil-patckin

## Description
The Field component cannot identify that user entered an invalid date in Datepicker. 

## Screenshots

https://user-images.githubusercontent.com/124583895/223055151-6a1c0780-b933-4d80-b44b-176ee4b95825.mov

## Issues
[STCOM-1110](https://issues.folio.org/browse/STCOM-1110)

2023-03-06 16:08 UTC, JohnC-80 commented
This is good for the particular case for now... The component will probably need to include its own internal validation indicator to let the user know that the value they've entered is an invalid one.

2023-03-06 16:08 UTC, JohnC-80 approved these changes

2023-03-06 17:15 UTC, BogdanDenis approved these changes

2023-03-08 10:59 UTC, BogdanDenis requested changes
Is this a PR for STCOM-1130 or STCOM-1110?
On scrum board 1130 is in progress, but here 1110 is mentioned.
Also please update CHANGELOG

2023-03-09 13:28 UTC, zburke commented
@daniil-patckin, saying that STCOM-1130/UIMARCAUTH-245 is the blocker to this one implies that work must be done in UIMARCAUTH before this issue can be resolved. That is backwards; the UIMARCAUTH problem is _caused_ by this bug. Indeed, an STCOM issue _cannot_ be blocked by any ui-$application issue because STCOM does not depend on any UI application. When both tickets were in STCOM, this confusion is what led me to move 1130 to "In code review". 

Thank you for adding a CHANGELOG entry. In the future, please use commit subjects and CHANGELOG entries that describe what is changing, i.e. that describe the fix, instead of describing the bug. These values should describe the state of the code after the change is committed, e.g. "Datepicker correctly shows validation warnings".

2023-03-09 18:10 UTC, merged