STCOM-1150: Remove unchecked call to Moment.locale
folio-org/stripes-components pull request #2025
Opened 2023-04-14 00:26 UTC by ncovercash

# [Jira STCOM-1150](https://issues.folio.org/browse/STCOM-1150)

This fixes the bug reported in [STCOM-1150](https://issues.folio.org/browse/STCOM-1150) and causing [UICAL-267](https://issues.folio.org/browse/UICAL-267) by removing the erroneous call to `moment.locale`.

To summarize [this Slack thread](https://folio-project.slack.com/archives/C210UCHQ9/p1680101882014399), the call to `moment.locale` for locales unknown to Moment (such as `en-SE` for Swedish English) caused Moment to fallback to default locale settings, however, it would also cache these default settings as the correct locale for `en-SE`.  When `Timepicker` later checked to see if Moment knew the locale, Moment then reported that it did, returning incorrectly assumed locale information, resulting in 24-hour `Timepicker`s switching to 12-hour at reconstruction.

Since the `locale` prop was only used by `TimeDropdown` for the `moment.locale` call, the prop was able to be removed too.

@JohnC-80 / @zburke one of y'all will likely want to clone this branch over to `folio-org` to check CI (I don't have permissions here), however, running tests locally revealed no new breaking tests (the only date-related failure was due to the change of the space in locale times in browser spaces (replaced with `\u202f`), however, that is outside the scope of this PR and issue.

2023-04-14 13:05 UTC, JohnC-80 approved these changes

2023-04-14 19:33 UTC, zburke commented
[Reference for those `\u202f` changes](https://github.com/nodejs/node/issues/46123). So much fun. 🙄

2023-04-14 21:39 UTC, ncovercash commented
> [Reference for those `\u202f` changes](https://github.com/nodejs/node/issues/46123). So much fun. 🙄

Every time I deal with weird time zone/localization bugs, I am reminded of [this amazing video](https://www.youtube.com/watch?v=-5wpm-gesOY)

2023-04-15 11:31 UTC, zburke commented
Ha! Great video, and he sure gets the moral correct (make somebody else do this if possible)! It's no small wonder that date/time pickers seem to always be the missing components in every single OSS component library!

I remember learning about unix in college and being totally bowled over by the command `cal 9 1752`. Part of it was the specific programming challenges, but more it was the eye-opening experience that something I'd thought was simple was actually really REALLY complicated, interesting, contentious, that a "factual" thing like the date could even _be_ contentious, etc.

2023-04-19 11:13 UTC, zburke requested changes
I believe moment is case-senstive WRT locales so those tests need to check for the exact same locale provided as the prop.

2023-04-19 11:13 UTC, zburke commented on lib/Datepicker/tests/Datepicker-test.js
> +
I believe moment is case-sensitive WRT locales so we need to check for `en-SE` here.

2023-04-19 11:13 UTC, zburke commented on util/dateTimeUtils.js
> +  return format.replaceAll('\u202f', ' ');
I agree with this change, but please add comment, e.g. a link to https://github.com/nodejs/node/issues/46123. Without any context, it's pretty opaque

2023-04-19 11:13 UTC, zburke commented on lib/Timepicker/tests/Timepicker-test.js
> +    it('does not poison moment locale cache', () => expect(moment.locales()).to.not.include('en-se'));
en-SE

2023-04-19 12:32 UTC, ncovercash commented on lib/Datepicker/tests/Datepicker-test.js
> +
Checked; moment will add both the string with its original casing and another in all lowercase

2023-04-19 17:07 UTC, ncovercash commented on lib/Timepicker/tests/Timepicker-test.js
> +    it('does not poison moment locale cache', () => expect(moment.locales()).to.not.include('en-se'));
see comments on other one

2025-04-09 14:02 UTC, JohnC-80 commented
Closing this due to age/time moving forward and future releases helping this issue in their moment locale-picking logic.. and also DayJS here we come!

2025-04-09 14:02 UTC, closed without merging