STCOM-1171 - expand options of meta section component
folio-org/stripes-components pull request #2082
Opened 2023-06-20 03:44 UTC by Terala-Priyanka

2023-06-20 19:23 UTC, JohnC-80 requested changes

2023-06-20 19:23 UTC, JohnC-80 commented on lib/MetaSection/MetaSection.js
> +  noBackGround: false,
The boolean props(`inlineLayout`, and `noBackGround` here) that default to false don't need a default prop... they'll just be undefined/falsey.

2023-06-20 19:23 UTC, JohnC-80 commented on lib/MetaSection/MetaSection.js
> +        style={inlineLayout ? { display: 'flex' } : { display: 'flex column' }
It will be better to bake these values out into CSS classes for testability of this and use the `classnames` dependency to functionally apply them - Then you can assert on classnames vs digging into style attribute values and the actual implemenation of those classes/values would be hidden away.

2023-06-20 19:23 UTC, JohnC-80 commented on lib/MetaSection/MetaSection.js
> +          'background-color': `${noBackGround ? 'unset' : 'var(--color-fill)'}`
Same as the `inlineLayout` comment above. The more of these inline styles that could be cleaned up by moving them to CSS classes, the better.

2023-06-22 08:40 UTC, JohnC-80 approved these changes

2023-06-22 13:46 UTC, BogdanDenis approved these changes

2023-06-22 13:53 UTC, merged