STCOM-1183: Provide the searchableOptions prop to the SearchField component to use it as children for options in the Select component.
folio-org/stripes-components pull request #2090
Opened 2023-07-03 14:41 UTC by Dmytro-Melnyshyn

## Purpose
Provide the `searchableOptions` prop to the `SearchField` component to use it as `children` for options in the `Select` component to be able to utilize the `<optgroup>` tag and not just the `<option>`.

## Issues
[STCOM-1183](https://issues.folio.org/browse/STCOM-1183)

## Related PRs
[ui-inventory/pull/2195](https://github.com/folio-org/ui-inventory/pull/2195)
[stripes-acq-components/pull/710](https://github.com/folio-org/stripes-acq-components/pull/710)

## Screencast

https://github.com/folio-org/stripes-components/assets/77053927/d7f78f3c-cef9-4aa4-a502-1d42580fb705

2023-07-05 17:18 UTC, BogdanDenis requested changes

2023-07-05 17:18 UTC, BogdanDenis commented on lib/SearchField/SearchField.js
> +  searchableOptions: PropTypes.oneOfType([
Please update readme and descripbe this prop and how it's different from `searchableIndexes`

2023-07-06 13:21 UTC, Dmytro-Melnyshyn commented on lib/SearchField/SearchField.js
> +  searchableOptions: PropTypes.oneOfType([
Thanks for noticing, I added.

2023-07-06 15:39 UTC, BogdanDenis approved these changes

2023-07-07 13:40 UTC, Dmytro-Melnyshyn commented
Hi @JohnC-80 please take a look at this [PR](https://github.com/folio-org/stripes-components/pull/2090).

2023-07-10 14:08 UTC, JohnC-80 approved these changes
Looking good. Thank you! Could you please add a test for this prop?

2023-07-11 07:55 UTC, merged