STCOM-766 Accessibility | Repeatable Field Component
folio-org/stripes-components pull request #2215
Opened 2024-01-30 12:17 UTC by vashjs

2024-01-31 19:27 UTC, JohnC-80 requested changes
While I do like the elegance of this approach, the case where it's odd is if a row in the middle is removed - focus probably should not move in this case (just keep focus on the button of the row where it was clicked...)
![repeatable_middle](https://github.com/folio-org/stripes-components/assets/20704067/a4b508a8-2954-4860-8f79-cf809ec88d79)

2024-02-01 10:34 UTC, vashjs commented
> While I do like the elegance of this approach, the case where it's odd is if a row in the middle is removed - focus probably should not move in this case (just keep focus on the button of the row where it was clicked...) ![repeatable_middle](https://private-user-images.githubusercontent.com/20704067/301282415-a4b508a8-2954-4860-8f79-cf809ec88d79.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODI2NzEsIm5iZiI6MTcwNjc4MjM3MSwicGF0aCI6Ii8yMDcwNDA2Ny8zMDEyODI0MTUtYTRiNTA4YTgtMjk1NC00ODYwLThmNzktY2Y4MDllYzg4ZDc5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEwMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYWM2NTA1ZjdlNzEwOWRlNzExNTI3ZjNlMGJiY2ZlYWEwMTZlMjFkYTdkNzEyNmRhMzk3YTFhYmE0NTNkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxvTjLD5A31ejbgJVuCNyzVsbsblyaxfJ1pr5j8dfIs) [ ![repeatable_middle](https://private-user-images.githubusercontent.com/20704067/301282415-a4b508a8-2954-4860-8f79-cf809ec88d79.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODI2NzEsIm5iZiI6MTcwNjc4MjM3MSwicGF0aCI6Ii8yMDcwNDA2Ny8zMDEyODI0MTUtYTRiNTA4YTgtMjk1NC00ODYwLThmNzktY2Y4MDllYzg4ZDc5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEwMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYWM2NTA1ZjdlNzEwOWRlNzExNTI3ZjNlMGJiY2ZlYWEwMTZlMjFkYTdkNzEyNmRhMzk3YTFhYmE0NTNkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxvTjLD5A31ejbgJVuCNyzVsbsblyaxfJ1pr5j8dfIs) ](https://private-user-images.githubusercontent.com/20704067/301282415-a4b508a8-2954-4860-8f79-cf809ec88d79.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODI2NzEsIm5iZiI6MTcwNjc4MjM3MSwicGF0aCI6Ii8yMDcwNDA2Ny8zMDEyODI0MTUtYTRiNTA4YTgtMjk1NC00ODYwLThmNzktY2Y4MDllYzg4ZDc5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEwMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYWM2NTA1ZjdlNzEwOWRlNzExNTI3ZjNlMGJiY2ZlYWEwMTZlMjFkYTdkNzEyNmRhMzk3YTFhYmE0NTNkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxvTjLD5A31ejbgJVuCNyzVsbsblyaxfJ1pr5j8dfIs) [ ](https://private-user-images.githubusercontent.com/20704067/301282415-a4b508a8-2954-4860-8f79-cf809ec88d79.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODI2NzEsIm5iZiI6MTcwNjc4MjM3MSwicGF0aCI6Ii8yMDcwNDA2Ny8zMDEyODI0MTUtYTRiNTA4YTgtMjk1NC00ODYwLThmNzktY2Y4MDllYzg4ZDc5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEwMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYWM2NTA1ZjdlNzEwOWRlNzExNTI3ZjNlMGJiY2ZlYWEwMTZlMjFkYTdkNzEyNmRhMzk3YTFhYmE0NTNkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxvTjLD5A31ejbgJVuCNyzVsbsblyaxfJ1pr5j8dfIs)

Hi @JohnC-80, changed behavior based on your inputs + change class component to functional, because one day all of them will be moved anyway. So now we have 3 handled cases:

1. when user added something - focus will move to last added element 
2. when user removed something in middle, we will keep focus on same index where it was clicked (it's a little bit tricky and works only because we are using indexes as keys 😃, so in our case it's not a bug but feature )
3. when user removed last element in list, we don't do anything, because index with such element doesn't exist

Please check GIF:

![STCOM-766](https://github.com/folio-org/stripes-components/assets/86330150/ef788db8-f68a-4828-9bfc-e0cf270c5ec8)

2024-02-01 11:22 UTC, NikitaSedyx commented on hooks/usePrevius/usePrevious.js
> +export const usePrevious = (value) => {
usePrevious

2024-02-01 12:37 UTC, SergeYvas approved these changes

2024-02-02 12:05 UTC, NikitaSedyx commented
@vashjs you need to pin `polished` to make CI work

2024-02-02 12:45 UTC, NikitaSedyx commented on package.json
> +    "polished": "4.2.2",
it's not a dependency, you just need a resolution

2024-02-02 14:22 UTC, JohnC-80 approved these changes

2024-02-02 15:49 UTC, merged